version: "3.8"

services:
    localstack:
        image: localstack/localstack:latest
        container_name: localstack
        ports:
            - "4566:4566"
            - "4571:4571"
        environment:
            - DEBUG=1
            - DATA_DIR=/tmp/localstack/data # Local directory for saving persistent data
            - DEFAULT_REGION=us-east-1
            - LAMBDA_EXECUTOR=local #running lambda from local dir
            - LAMBDA_REMOTE_DOCKER=0
            - DOCKER_SOCK=unix:///var/run/docker.sock
            - HOST_TMP_FOLDER=/tmp/localstack
            # - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY- }  # only required for Pro
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
networks:
    default:
        name: localstack