name: RunTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    
    services:
      localstack:
        image: localstack/localstack:latest
        ports:
          - 4566:4566
          - 4569:4569
        env:
          LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt update && apt install git curl unzip build-essential -y
      - name: Install node
        run: |
          curl -fsSL https://deb.nodesource.com/setup_15.x | bash
          apt-get install -y nodejs
      - name: Setup Go environment
        uses: actions/setup-go@v3.0.0
        with:
          go-version: '>=1.17.0'
      - run: go version


      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0
        with:
          terraform_version: 1.1.7
          terraform_wrapper: false

      - name: Run the tests
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: cd ./test && go test -v